ALTER TABLE products ADD COLUMN sale_price TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN featured INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN bestseller INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN new_arrival INTEGER NOT NULL DEFAULT 0;
